import { Building2, Leaf, Users } from "lucide-react";
import type { AnalysisResponse, RiskResponse } from "@/types/polaris";
import { Chip, Panel, StatLine } from "./primitives";
import { RiskLevelChip } from "./SupportBadge";

const ICONS = {
  economic: Building2,
  environment: Leaf,
  social: Users,
} as const;

export function MultiDimensionalImpact({
  data,
  onOpenEvidence,
}: {
  data: AnalysisResponse;
  onOpenEvidence: (ids: string[]) => void;
}) {
  return (
    <Panel
      eyebrow="Multi-dimensional impact"
      title="Economic · Environment · Social"
      description={`Generated by ${data.generated_by}`}
    >
      <div className="grid gap-5 lg:grid-cols-3">
        {data.dimensions.map((d) => {
          const Icon = ICONS[d.dimension];
          return (
            <article key={d.dimension} className="rounded-xl border border-border bg-surface-raised/50 p-5">
              <div className="flex items-center justify-between gap-3">
                <h3 className="flex items-center gap-2 text-sm font-semibold capitalize text-foreground">
                  <Icon className="size-4 text-primary" aria-hidden />
                  {d.dimension}
                </h3>
                <Chip
                  tone={
                    d.direction === "positive" ? "positive" : d.direction === "mixed" ? "warning" : "danger"
                  }
                >
                  {d.score_label}
                </Chip>
              </div>
              <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{d.summary}</p>
              <ul className="mt-4 space-y-2">
                {d.points.map((p) => (
                  <li key={p} className="flex gap-2 text-sm text-muted-foreground">
                    <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary/70" aria-hidden />
                    {p}
                  </li>
                ))}
              </ul>
              <div className="mt-4">
                {d.metrics.map((m) => (
                  <StatLine key={m.label} label={m.label} value={m.value} />
                ))}
              </div>
              <button
                onClick={() => onOpenEvidence(d.evidence_ids)}
                className="mt-4 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground transition-colors hover:border-primary/40 hover:text-primary"
              >
                View {d.evidence_ids.length} sources
              </button>
            </article>
          );
        })}
      </div>

      <div className="mt-6 rounded-xl border border-primary/25 bg-primary/8 p-5">
        <p className="label-eyebrow">Recommendations</p>
        <ul className="mt-3 grid gap-2 md:grid-cols-2">
          {data.recommendations.map((r) => (
            <li key={r} className="flex gap-2 text-sm text-foreground">
              <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" aria-hidden />
              {r}
            </li>
          ))}
        </ul>
      </div>
    </Panel>
  );
}

export function RiskPanel({ data }: { data: RiskResponse }) {
  const blocks = [data.model_uncertainty, data.evidence_disagreement, data.data_limitations];
  return (
    <Panel
      eyebrow="Risk & uncertainty"
      title={`Overall risk: ${data.overall.label}`}
      action={<RiskLevelChip level={data.overall.level} />}
      description={`Composite risk score ${data.overall.score} / 100 as reported by the analysis service.`}
    >
      <div className="grid gap-5 lg:grid-cols-3">
        {blocks.map((b) => (
          <article key={b.title} className="rounded-xl border border-border bg-surface-raised/50 p-5">
            <div className="flex items-center justify-between gap-3">
              <h3 className="text-sm font-semibold text-foreground">{b.title}</h3>
              <RiskLevelChip level={b.level} />
            </div>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{b.summary}</p>
            <ul className="mt-4 space-y-2">
              {b.items.map((i) => (
                <li key={i} className="flex gap-2 text-sm text-muted-foreground">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-warning/70" aria-hidden />
                  {i}
                </li>
              ))}
            </ul>
          </article>
        ))}
      </div>
    </Panel>
  );
}
